Selinux Troubleshooting Guide
=============================
:Author: Matthew Sawyer
:Email: athias@protonmail.com
:Date: 14 May 2018
:toc:

== Introduction

This guide is intended to provide examples of commonly seen selinux errors.  Following a common scenario we will re-create these common issues, identify the selinux error, and correct the issue.

This is not intended to be the perfect answer to every situation, nor is it meant to answer highly complex selinux issues.

NOTE: This guide is based on Red Hat Enterprise Linux 7.  The specific steps used may differ when using other operating systems.

== The Scenarios

.Common selinux issues presented:
* selinux context not set correctly
* selinux boolean must be configured
* custom selinux policy must be created

.Scenarios displaying common issues:
* Web Hosted - Local RPM Repository
* Web Hosted - Custom System Data
* Web Hosted - Configuration Scripts
* NFS Home Directories

== Is it really selinux

Before you even begin troubleshooting, you should try a simple test to determine if selinux really is the issue.  This is the most basic test that answers the question - Does it work when selinux is turned off, and fail when selinux is turned back on?  To answer this question, we simply turn selinux off temporarily and verify it works.

===Example 1


----
Disable selinux
  # setenforce 0
Restart httpd
  # systemctl restart httpd

* # setenforce 1


